#!/usr/bin/env bash
# Having fun with "pure bash"
# Read basic memory stats and cpu usage in an alternate buffer that refreshes the data every 2 seconds
# an alternate buffer is a separate temporary screen

MEM_FILE=/proc/meminfo
CPU_FILE=/proc/stat
RED=$'\e[1;31m'
GREEN=$'\e[0;32m'
YELLOW=$'\e[0;33m'
TOTALS=$'\e[38;2;254;126;219m' 
RST=$'\e[0m'

# count cpus from /proc/stat using simple regex to match 'cpuNN'
count_cpus()
{
	cores=0
	while read -r core _; do
		[[ $core =~ ^cpu[0-9]+$ ]] && ((cores++))
	done < "$CPU_FILE"
}

# /proc/stat does not report current CPU utilization. The CPU fields are counters since boot
# To calculate usage, take two readings(read_cpu_1, read_cpu_2) 
# separate them by a time interval(this is done in the 'main' func below) and calculate
# Then it will measure how much CPU time was spent doing work rather than over the entire lifetime of the system
read_cpu_1()
{
	read -r _ user1 nice1 system1 idle1 iowait1 irq1 softirq1 steal1 _ _ < "$CPU_FILE"
	busy1=$(( user1 + nice1 + system1 + irq1 + softirq1 + steal1 ))
	total1=$(( busy1 + idle1 + iowait1 ))
}

read_cpu_2()
{
	read -r _ user2 nice2 system2 idle2 iowait2 irq2 softirq2 steal2 _ _ < "$CPU_FILE"
	busy2=$(( user2 + nice2 + system2 + irq2 + softirq2 + steal2 ))
	total2=$(( busy2 + idle2 + iowait2 ))
	busy_total=$(( busy2 - busy1 ))
	cpu_total=$(( total2 - total1 ))
	cpu_usage=$(( 100 * busy_total / cpu_total ))
}


# Update color vars based on percentage
get_color() {
	local percent=$1

	if (( percent >= 60 )); then
		printf '%s' "$RED"
	elif (( percent >= 40 )); then
		printf '%s' "$YELLOW"
	else
		printf '%s' "$GREEN"
	fi
}

# Read and format memory output
get_memory()
{
	printf -v now '%(%Y-%m-%d %H:%M:%S)T'
	echo -e "Memory Usage on $HOSTNAME - $now\n"
	while IFS=":" read -r key value; do
		case "$key" in 
			"MemTotal") mem_total=$(( ${value/kB} / 1024 )) ;;
			"MemAvailable") mem_avail=$(( ${value/kB} / 1024 )) ;;
			"SwapTotal") swap_total=$(( ${value/kB} / 1024 )) ;;
			"SwapFree") swap_free=$(( ${value/kB} / 1024 )) ;;
		esac
	done < "$MEM_FILE"

	mem_used=$(( mem_total - mem_avail )) 
	mem_perc=$(( mem_used * 100 / mem_total )) 
	swap_used=$(( swap_total - swap_free ))
	swap_perc=$(( swap_used * 100 / swap_total ))

	color=$(get_color "$mem_perc")
	color2=$(get_color "$swap_perc")
	color3=$(get_color "$cpu_usage")

	printf "%s%-11s\n\t%6d MiB (%d%%)%s\n" "$color" "MemUsed:" "$mem_used" "$mem_perc" "$RST"
	printf "%s%-11s\n\t%6d MiB%s\n" "$color" "MemAvail:"  "$mem_avail" "$RST"
	printf "%s%-11s\n\t%6d MiB%s\n" "$TOTALS" "MemTotal:"  "$mem_total" "$RST"
	printf "%s%-11s\n\t%6d MiB (%d%%)%s\n" "$color2" "SwapUsed:"  "$swap_used" "$swap_perc" "$RST"
	printf "%s%-11s\n\t%6d MiB%s\n" "$color2" "SwapFree:"  "$swap_free" "$RST"
	printf "%s%-11s\n\t%6d MiB%s\n" "$TOTALS" "SwapTotal:" "$swap_total" "$RST"
	printf "%s%-11s\n\t%6d cpus (%d%%)%s\n" "$color3" "CPU Usage:" "$cores" "$cpu_usage" "$RST"
}

# Stolen from https://github.com/dylanaraps/pure-bash-bible#use-read-as-an-alternative-to-the-sleep-command
read_sleep() {
	# Usage: read_sleep 1
	#        read_sleep 0.2
	read -rt "$1" <> <(:) || :
}

# Return to main screen and show cursor
cleanup()
{
	printf '\e[?1049l' # disable alternate buffer
	printf '\e[?25h' # show the cursor
}

main()
{
	count_cpus
	trap cleanup EXIT
	printf '\e[?1049h' # enable alternate buffer
	printf '\e[?25l' # hide the cursor
	printf '\e[H' # move the cursor home
	while true; do
		read_cpu_1
		get_memory
		read_sleep 2
		read_cpu_2
		printf '\e[2J' # clear the screen
		printf '\e[H' # move the cursor home
	done
}

main
