#!/usr/bin/env bash
# Write an .iso or .img file to a USB using dd
# May need to unmount partitions of device prior if there are any(e.g.): 'sudo umount /dev/sda*'

# Takes a string as an argument to provide colored output
info()
{
    echo -e "\n\033[1;32m==> $*\033[0m"
}

read -rp "Enter directory containing ISO image: " iso_dir

if [[ ! -d "$iso_dir" ]];then
	echo "$iso_dir not found"
	exit 1
fi

mapfile -t iso < <(find "$iso_dir" -maxdepth 1 -type f \( -name "*.iso" -o -name "*.img" \))

if [[ ${#iso[@]} -eq 0 ]];then
	echo "No iso files in $iso_dir"
	exit 1
fi

info "Available iso's in $iso_dir:"
for i in "${!iso[@]}";do
	echo "[$i] ${iso[$i]##*/}"
done

read -rp "Enter number for ISO to write to USB: " iso_num
img=${iso[$iso_num]}
[[ -z $img ]] && { echo "Incorrect input: $iso_num"; exit 1; }

mapfile -t block < <(lsblk -no PATH)

info "Available devices:"
for j in "${!block[@]}";do
	echo "[$j] ${block[$j]}"
done

read -rp "Enter number for device to write to: " blk_num
device=${block[$blk_num]}
[[ -z $device ]] && { echo "Incorrect input: $blk_num"; exit 1; }

info "Your final selections:"
echo "ISO:	 $img"
echo "Device:  $device"

read -rp "This will erase all data on ${device}! Continue? (y/N): " confirm

if [[ "$confirm" != [yY] ]];then 
	echo "Aborted"
	exit 1
fi

info "Writing to ${device}..."
sudo dd if="$img" of="$device" bs=4M status=progress conv=fsync

info "Ejecting $device..."
sudo eject "$device"

info "Finished writing $img to $device"
