#!/usr/bin/env bash
# Having fun with "pure bash"
# Read basic memory stats from /proc/meminfo 
# in an alternate buffer that refreshes the data every 2 seconds

FILE=/proc/meminfo
CYAN=$'\e[38;5;16;48;2;3;237;249m' 
RED=$'\e[1;31m'
GREEN=$'\e[0;32m'
YELLOW=$'\e[0;33m'
TOTALS=$'\e[38;2;254;126;219m' 
RST=$'\e[0m'

# Update color vars based on percentage
get_color() {
  local percent=$1

  if (( percent >= 60 )); then
      printf '%s' "$RED"
  elif (( percent >= 40 )); then
      printf '%s' "$YELLOW"
  else
      printf '%s' "$GREEN"
  fi
}

# Read and format memory output
get_memory()
{
	printf -v now '%(%Y-%m-%d %H:%M:%S)T'
	echo -e "${CYAN}Memory Usage on $HOSTNAME - $now${RST}\n"
	while IFS=":" read -r key value; do
		case "$key" in 
			"MemTotal") mem_total=$(( ${value/kB} / 1024 )) ;;
			"MemFree") mem_free=$(( ${value/kB} / 1024 )) ;;
			"MemAvailable") mem_avail=$(( ${value/kB} / 1024 )) ;;
			"SwapTotal") swap_total=$(( ${value/kB} / 1024 )) ;;
			"SwapFree") swap_free=$(( ${value/kB} / 1024 )) ;;
		esac
	done < "$FILE"

	mem_used=$(( mem_total - mem_avail )) 
	mem_perc=$(( mem_used * 100 / mem_total )) 
	swap_used=$(( swap_total - swap_free ))
	swap_perc=$(( swap_used * 100 / swap_total ))

  color=$(get_color "$mem_perc")
  color2=$(get_color "$swap_perc")

	printf "%s%-11s\n\t%6d MiB (%d%%)%s\n" "$color" "MemUsed:" "$mem_used" "$mem_perc" "$RST"
	printf "%s%-11s\n\t%6d MiB%s\n" "$color" "MemAvail:"  "$mem_avail" "$RST"
	printf "%s%-11s\n\t%6d MiB%s\n" "$TOTALS" "MemTotal:"  "$mem_total" "$RST"
	printf "%s%-11s\n\t%6d MiB (%d%%)%s\n" "$color2" "SwapUsed:"  "$swap_used" "$swap_perc" "$RST"
	printf "%s%-11s\n\t%6d MiB%s\n" "$color2" "SwapFree:"  "$swap_free" "$RST"
	printf "%s%-11s\n\t%6d MiB%s\n" "$TOTALS" "SwapTotal:" "$swap_total" "$RST"
}

# Stolen from https://github.com/dylanaraps/pure-bash-bible#use-read-as-an-alternative-to-the-sleep-command
read_sleep() {
	# Usage: read_sleep 1
	#        read_sleep 0.2
	read -rt "$1" <> <(:) || :
}

# Return to main screen and show cursor
cleanup()
{
	printf '\e[?1049l' # disable alternate buffer
	printf '\e[?25h' # show the cursor
}

main()
{
	# an alternate buffer is a separate temporary screen
	trap cleanup EXIT
	printf '\e[?1049h' # enable alternate buffer
	printf '\e[?25l' # hide the cursor
	printf '\e[H' # move the cursor home
	while true; do
		get_memory
		read_sleep 2
		printf '\e[2J' # clear the screen
		printf '\e[H' # move the cursor home
	done
}

main
