#!/usr/bin/env bash
# Quickly create blank bash script templates
# Takes one or more script names as arguments,
# creates the files in the curent directory if they don't exist, 
# and give the current user executable permissions

usage()
{
	echo "Usage: ${0##*/} $@"
}

[[ $# -lt 1 ]] && usage "<arg1>" "[arg2..]" && exit 1
	
for arg in "$@"
do
	if [[ -e $arg ]]; then
		echo "'$arg' already exists. Skipping.."
		continue
	else
		echo '#!/usr/bin/env bash' > "$arg"
		chmod u+x "$arg"
		echo "---------------------------"
		echo "Created:  $arg"
		echo "Perms:    $(ls -l "$arg")"
		echo "---------------------------"
	fi
done
